# Generated by Django 3.0.10 on 2020-10-06 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('document_collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_standards_definition.DocumentCollection')),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('file_filed_name', models.CharField(blank=True, max_length=200)),
                ('tag_name', models.CharField(max_length=200)),
                ('unit', models.CharField(blank=True, max_length=100)),
                ('data_min_length', models.IntegerField(default=-1)),
                ('data_max_length', models.IntegerField(default=-1)),
                ('data_type', models.CharField(max_length=100)),
                ('data_collection_device', models.CharField(blank=True, max_length=100)),
                ('data_collection_period', models.CharField(blank=True, max_length=100)),
                ('data_transper_period', models.CharField(blank=True, max_length=100)),
                ('value', models.CharField(blank=True, max_length=100)),
                ('original_value', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('etc', models.TextField(blank=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_standards_definition.Document')),
            ],
        ),
        migrations.AddConstraint(
            model_name='content',
            constraint=models.UniqueConstraint(fields=('tag_name', 'document'), name='unique_constraints'),
        ),
    ]
