# Generated by Django 3.0.10 on 2020-10-06 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_standards_definition', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='content',
            name='unique_constraints',
        ),
        migrations.AddConstraint(
            model_name='content',
            constraint=models.UniqueConstraint(fields=('tag_name', 'document'), name='unique_tag_name_document_constraints'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.UniqueConstraint(fields=('name', 'document_collection'), name='unique_name_document_collection_constraints'),
        ),
    ]
